---
- name: Ensure required variables are defined
  fail: msg="{{ item }} value missing and is required"
  when: "item is not defined"
  with_items:
    - client
    - pki_password
    - ovpn_data

- name: check if ovpn container is running
  shell: "docker ps|grep ovpn"
  register: ovpn

- assert:
    that: ovpn.stdout_lines|length > 0

- name: generate client credentials
  shell: |
    docker run -e PKI_PASS='{{ pki_password }}' \
    -v {{ ovpn_data }}:/etc/openvpn \
    --rm kylemanna/openvpn \
    /etc/openvpn/with_pass.sh easyrsa build-client-full {{ client }} nopass
  args:
    creates: "{{ ovpn_data }}pki/issued/{{ client }}.crt"
  no_log: true

- name: export client credentials
  shell: |
    docker run \
    -v {{ ovpn_data }}:/etc/openvpn \
    --rm kylemanna/openvpn \
    /etc/openvpn/with_pass.sh ovpn_getclient {{ client }} > {{ client }}.ovpn
  args:
    creates: "{{ ovpn_data }}client_confs/{{ client }}.ovpn"
    chdir: "{{ ovpn_data }}client_confs"

- name: download the new configs
  fetch:
    src: "{{ ovpn_data }}client_confs/{{ client }}.ovpn"
    dest: ovpn_configs/
    flat: yes

- name: configure static IP
  include: configure_static_ip.yaml
  when: ip is defined

# docker run -v $OVPN_DATA:/etc/openvpn --rm kylemanna/openvpn ovpn_getclient CLIENTNAME > CLIENTNAME.ovpn
